# Generated by Django 3.2.5 on 2021-07-26 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название категории')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='DefaultTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст задачи')),
                ('content', models.TextField(verbose_name='Контент задачи')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefaultTaskVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер варианта')),
                ('answer', models.CharField(max_length=128, verbose_name='Ответ')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='tasks.defaulttask', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Вариант задания',
                'verbose_name_plural': 'Варианты задания',
            },
        ),
        migrations.CreateModel(
            name='VariableForDefaultTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название переменной')),
                ('value', models.CharField(max_length=256, verbose_name='Значение')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='tasks.defaulttaskvariant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Переменная для варианта',
                'verbose_name_plural': 'Переменные для варианта',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
                ('type', models.CharField(choices=[('T', 'Test'), ('MT', 'Multiple Test'), ('D', 'DEFAULT')], default='D', max_length=10, verbose_name='Тип задачи')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.AddField(
            model_name='defaulttask',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
