# Generated by Django 3.2.5 on 2021-07-01 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер варианта')),
                ('answer', models.CharField(max_length=128, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вариант задания',
                'verbose_name_plural': 'Варианты задания',
            },
        ),
        migrations.CreateModel(
            name='VariantVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=32, verbose_name='Переменная')),
                ('value', models.CharField(max_length=256, verbose_name='Значение')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.variant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Переменная для варианта',
                'verbose_name_plural': 'Переменные для варианта',
            },
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AddField(
            model_name='task',
            name='grade',
            field=models.IntegerField(default=5, verbose_name='Максимальная оценка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='option_count',
            field=models.IntegerField(default=4, verbose_name='Количество вариантов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='withSelfChecking',
            field=models.BooleanField(default=False, verbose_name='Самопроверяемый'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='variant',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Задание'),
        ),
    ]
