# Generated by Django 3.2.5 on 2021-07-02 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_user_task_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='tasks.task', verbose_name='Задание'),
        ),
    ]
