# Generated by Django 3.2.5 on 2021-07-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_variant_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='option_count',
            field=models.IntegerField(default=0, verbose_name='Количество вариантов'),
        ),
    ]
