# Generated by Django 3.2.5 on 2021-07-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_rename_variantvariable_variable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variable',
            old_name='option',
            new_name='variant',
        ),
    ]
