# Generated by Django 3.2.5 on 2021-07-02 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_rename_option_variable_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='tasks.variant', verbose_name='Вариант'),
        ),
    ]
