# Generated by Django 3.2.5 on 2021-07-01 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_auto_20210701_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(verbose_name='Результат')),
                ('max_result', models.IntegerField(verbose_name='Максимальный результат')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
            },
        ),
        migrations.CreateModel(
            name='TaskAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=128, verbose_name='Ответ пользователя')),
                ('correct_answer', models.CharField(max_length=128, verbose_name='Правильный ответ')),
                ('grade', models.IntegerField(verbose_name='Оценка')),
                ('max_grade', models.IntegerField(verbose_name='Максимальная оценка')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.attempt')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название соревнования')),
                ('start', models.DateTimeField(null=True, verbose_name='Начало')),
                ('finish', models.DateTimeField(null=True, verbose_name='Конец')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('tasks', models.ManyToManyField(to='tasks.Task')),
            ],
            options={
                'verbose_name': 'Соревнование',
                'verbose_name_plural': 'Соревнования',
            },
        ),
        migrations.AddField(
            model_name='attempt',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.competition', verbose_name='Соревнование'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
